### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by jgjc222** [Treeki/BirdBridge#1]
Hi, thank you for this amazing bridge. I'm facing an issue loading tweet replies, I assume because it uses API v2 while all other functionalities use v1 (my app is really old, I don't have permission to use v2). Any chance you can fix that?
edit: I think I understand, twitter didn't implement tweet replies until v2. Hopefully I got that wrong?

**Comment by zhuowei** [comment]
I think https://github.com/Treeki/BirdBridge/blob/634de09928c8239f920851d4493cad9b091668f7/main.ts#L417 may actually use an API that's [only available](https://twitter.com/428rinsuki/status/1614944457950130176) for Twitter's official app API keys (it's a /2/ API that ends in `.json`).

You could try it with one of those keys.

**Comment by jgjc222** [comment]
Ah clear, thank you for the clarification!
